### ISSUE TITLE
send boardKey in request body

### ISSUE THREAD

**Issue by mittalmehul** [bmdvpanga/tictactoe#21]
FE is not sending the request. body at route /games/<gameid> causing an internal server error

**Comment by chris-wolff** [comment]
@mittalmehul Thanks for pointing this out. You're talking about something like `localhost:5000/games/1` and the fetch call in Tile.js, line 32? Because just /games shouldn't have a body at all to my knowledge, just a URL. 

I resolved the body thing for `localhost:5000/games/1` with a recent pull request, I believe.

**Comment by chris-wolff** [comment]
@mittalmehul Thanks for contributing!
